// Awful Answers Card Database
// Black cards are prompts/questions with blanks
// White cards are answers to fill in the blanks

const blackCards = [
    // Fill in the blank (single)
    "I got 99 problems but _____ ain't one.",
    "What's that smell? _____.",
    "_____ is a slippery slope that leads to _____.",
    "In M. Night Shyamalan's new movie, Bruce Willis discovers that _____ had really been _____ all along.",
    "What's the next Happy Meal toy? _____.",
    "It's a pity that kids these days are all getting involved with _____.",
    "In the new Disney Channel Original Movie, Hannah Montana struggles with _____ for the first time.",
    "Alternative medicine is now embracing the curative powers of _____.",
    "What ended my last relationship? _____.",
    "MTV's new reality show features eight washed-up celebrities living with _____.",
    "I drink to forget _____.",
    "I never truly understood _____ until I encountered _____.",
    "What's my secret power? _____.",
    "Maybe she's born with it. Maybe it's _____.",
    "What's the most emo? _____.",
    "Life for American Indians was forever changed when the White Man introduced them to _____.",
    "Next from J.K. Rowling: Harry Potter and the Chamber of _____.",
    "A romantic candlelit dinner would be incomplete without _____.",
    "What's there a ton of in heaven? _____.",
    "What's my anti-drug? _____.",
    "_____ is so hot right now.",
    "Coming to Broadway this season, _____: The Musical.",
    "What gives me uncontrollable gas? _____.",
    "When I am a billionaire, I shall erect a 50-foot statue to commemorate _____.",
    "What's the gift that keeps on giving? _____.",
    "Tonight on 20/20: The Story of _____.",
    "_____ + _____ = _____.",
    "During sex, I like to think about _____.",
    "The class field trip was completely ruined by _____.",
    "Before I run for president, I must destroy all evidence of my involvement with _____.",
    "What will always get you laid? _____.",
    "What am I giving up for Lent? _____.",
    "When I was tripping on acid, _____ turned into _____.",
    "Why can't I sleep at night? _____.",
    "What's that sound? _____.",
    "What helps Obama unwind? _____.",
    "What did I bring back from Mexico? _____.",
    "Major League Baseball has banned _____ for giving players an unfair advantage.",
    "When Pharaoh remained unmoved, Moses called down a Plague of _____.",
    "TSA guidelines now prohibit _____ on airplanes.",
    "_____ would be woefully incomplete without _____.",
    "In L.A. County Jail, word is you can trade 200 cigarettes for _____.",
    "What would grandma find disturbing, yet oddly charming? _____.",
    "What did the U.S. airdrop to the children of Afghanistan? _____.",
    "What's Teach for America using to inspire inner city students to succeed? _____.",
    "Studies show that lab rats navigate mazes 50% faster after being exposed to _____.",
    "What don't you want to find in your Chinese food? _____.",
    "What's the new fad diet? _____.",
    "What did Vin Diesel eat for dinner? _____.",
    "_____ is a gateway to _____.",

    // Pick 2 variations
    { text: "Make a haiku.", pick: 2 },
    { text: "_____ is a slippery slope that leads to _____.", pick: 2 },
    { text: "I got 99 problems but _____ ain't one.", pick: 1 },
    { text: "What's that smell? _____.", pick: 1 },
    { text: "Step 1: _____. Step 2: _____. Step 3: Profit.", pick: 2 },
    { text: "I never truly understood _____ until I encountered _____.", pick: 2 },
    { text: "In M. Night Shyamalan's new movie, Bruce Willis discovers that _____ had really been _____ all along.", pick: 2 },
    { text: "_____ + _____ = _____.", pick: 3 },
    { text: "When I was tripping on acid, _____ turned into _____.", pick: 2 },
    { text: "_____ would be woefully incomplete without _____.", pick: 2 },
    { text: "What's the next superhero/villain duo? _____ & _____.", pick: 2 },
    { text: "_____ is a gateway to _____.", pick: 2 },
    { text: "Lifetime presents _____: the story of _____.", pick: 2 },
    { text: "In his new self-produced album, Kanye West raps over the sounds of _____.", pick: 1 },
    { text: "This is your captain speaking. Fasten your seatbelts and prepare for _____.", pick: 1 }
];

const whiteCards = [
    // Nouns and phrases
    "A tiny horse",
    "Laser hair removal",
    "An Oedipus complex",
    "Pretending to care",
    "Soup that is too hot",
    "The hardworking Mexican",
    "Chunks of dead hitchhiker",
    "Dying",
    "Coat hanger abortions",
    "A windmill full of corpses",
    "Swooping",
    "Explosions",
    "A sausage festival",
    "A mime having a heart attack",
    "An M. Night Shyamalan plot twist",
    "Sean Penn",
    "Vigorous jazz hands",
    "Kamikaze pilots",
    "Horrifying laser hair removal accidents",
    "Testicular torsion",
    "Stranger danger",
    "Erectile dysfunction",
    "Being marginally famous",
    "A squadron of moles wearing aviator goggles",
    "Public ridicule",
    "The forbidden fruit",
    "Chainsaws for hands",
    "Poorly-timed Holocaust jokes",
    "An icepick lobotomy",
    "Raptor attacks",
    "The Make-A-Wish Foundation",
    "Daddy issues",
    "Viagra",
    "Hot cheese",
    "A salty surprise",
    "Authentic Mexican cuisine",
    "Black people",
    "Dead parents",
    "Elderly Japanese men",
    "The penny whistle solo from 'My Heart Will Go On'",
    "Genetically engineered super-soldiers",
    "A Bop It",
    "Agriculture",
    "Tangled Slinkys",
    "Saxophone solos",
    "Doing the right thing",
    "A can of whoop-ass",
    "Horse meat",
    "Slow motion",
    "Powerful thighs",
    "Spontaneous human combustion",
    "Sniffing glue",
    "A really cool hat",
    "A mating display",
    "Preteens",
    "An AR-15 assault rifle",
    "My humps",
    "A defective condom",
    "A pyramid of severed heads",
    "Sunshine and rainbows",
    "Finger painting",
    "Getting drunk on mouthwash",
    "Skeletons",
    "Panda sex",
    "Flightless birds",
    "Passive-aggressive Post-it notes",
    "Consultants",
    "The Holy Bible",
    "Ronald Reagan",
    "Shaquille O'Neal's acting career",
    "The Three-Fifths Compromise",
    "Not giving a shit about the Third World",
    "A Gypsy curse",
    "Amputees",
    "An asymmetric boob job",
    "Liberal activists",
    "Friendly fire",
    "Historically black colleges",
    "Shapeshifters",
    "Rush Limbaugh's soft, shitty body",
    "Emotions",
    "Sexting",
    "Men",
    "Swooping",
    "Women in yogurt commercials",
    "Nocturnal emissions",
    "The violation of our most basic human rights",
    "Serfdom",
    "A murder most foul",
    "Crippling debt",
    "The invisible hand",
    "The Big Bang",
    "Pooping back and forth. Forever",
    "Toni Morrison's vagina",
    "The placenta",
    "Same-sex ice dancing",
    "A lifetime of sadness",
    "Teaching a robot to love",
    "Smallpox blankets",
    "Puppies!",
    "An erection that lasts longer than four hours",
    "Wet dreams",
    "Dead babies",
    "Nazis",
    "World peace",
    "Free samples",
    "Grandma",
    "Global warming",
    "The terrorists",
    "Sexism",
    "Racism",
    "The patriarchy",
    "Science",
    "Party poopers",
    "Sipping champagne on a yacht",
    "Breaking out into song and dance",
    "Pooping",
    "Farting and walking away",
    "Hope",
    "Crushing disappointment",
    "Sweet, sweet vengeance",
    "My relationship status",
    "Getting really high",
    "Student loans",
    "WiFi",
    "Getting rejected by Harvard",
    "The placebo effect",
    "New Age music",
    "Eating an entire snowman",
    "Waking up in a hotel bathtub filled with ice",
    "Licking things to claim them as your own",
    "Snorting cocaine off a striper's buttocks",
    "Soup that is too cold",
    "Britney at age 55",
    "Being a busy adult with many important things to do",
    "Civilian casualties",
    "A foul mouth",
    "Unfathomable stupidity",
    "A bloody pacifier",
    "Overcompensation",
    "Throwing a virgin into a volcano",
    "Child beauty pageants",
    "Heteronormativity",
    "Lactation",
    "Centaurs",
    "Scrotum tickling",
    "Dick fingers",
    "A good sniff",
    "Shiny objects",
    "Natural selection",
    "Kids with ass cancer",
    "Prancing",
    "The chronic",
    "Darth Vader",
    "A zesty breakfast burrito",
    "The Underground Railroad",
    "Necrophilia",
    "Wifely duties",
    "Figgy pudding",
    "Cheating in the Special Olympics",
    "Wearing underwear inside-out to avoid doing laundry",
    "The American Dream",
    "Switching to Geico",
    "German dungeon porn",
    "Bees?",
    "Inappropriate yodeling",
    "Goblins",
    "Being on fire",
    "Full frontal nudity",
    "Frolicking",
    "Take-backsies",
    "My vagina",
    "The Force",
    "Cybernetic enhancements",
    "Exactly what you'd expect",
    "The clitoris",
    "Picking up a hitchhiker",
    "Actually getting shot, for real",
    "Muhammad (praise be unto him)",
    "72 virgins",
    "Incest",
    "An uppercut",
    "Object permanence",
    "Half-assed foreplay",
    "Ghosts",
    "Cards Against Humanity",
    "Ripping into a man's chest and pulling out his still-beating heart",
    "Me time",
    "Flesh-eating bacteria",
    "A good time",
    "Wiping her butt",
    "A balanced breakfast",
    "A hot mess",
    "Italians"
];

module.exports = {
    blackCards,
    whiteCards
};
